#!/bin/bash 
# $1 - user
# $2 - directory
# $3 - output file
if [ $# -ne 3 ] 
then
  echo "Wrong parametrs: param1 - user
                         param2 - directory
                         param3 - output file" >&2
elif [ ! -d $2 ] 
then 
  echo "Error: $2 is not a directory" >&2
else
  if ! id "$1" &> /dev/null
  then
    echo 'Error: no username found' >&2
  else
    way="`realpath -e "$2"`"
    find "$way" -type f -user "$1" -printf '%p\t%s\n' >"$3"
    echo -n "Number of watched files: "
    find "$2" -type f | wc -l
  fi
fi
