#!/bin/bash 
# $1 - user
# $2 - directory
# $3 - output file
if [ $# -ne 3 ] 
then
  echo "Wrong parametrs: param1 - user
                         param2 - directory
                         param3 - output file" >&2
elif [ ! -d $2 ] 
then 
  echo "Error: $2 is not a directory" >&2
else
  find "$2" -user "$1" -type f -fprintf "$3" '%h\t%f\t%s\n'
  echo -n "Number of watched files: "
  find "$2" -type f | wc -l
fi
