#!/bin/bash
#$1 - source
#$2 - exe
if [ $# -ne 2 ]
  then
  echo "Wrong parametrs: param1 - source file
                         param2 - name of .exe file" >&2
else 
  gcc "$1" -o "$2.exe"  && ./"$2.exe"
fi
